#### Section A: Data Structures & Control Structures

1. Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse

In [20]:
lst = [5,6,8,9,1] #creating list of 5 integers

In [21]:
lst.append(7) #append() used to add integer 

In [22]:
lst

[5, 6, 8, 9, 1, 7]

In [23]:
lst.extend([10,11,12]) #it's loops through every item and adds it to the original list
lst

[5, 6, 8, 9, 1, 7, 10, 11, 12]

In [24]:
lst.insert(2,3) #insert() is used to add item in any location specified in our case at index=2, item 3 is inserted
lst

[5, 6, 3, 8, 9, 1, 7, 10, 11, 12]

In [25]:
lst.remove(3) #remove() is used to remove specific item by it's value not by it's index
lst

[5, 6, 8, 9, 1, 7, 10, 11, 12]

In [26]:
lst.pop() #pop() is used to remove last item from the list
lst

[5, 6, 8, 9, 1, 7, 10, 11]

In [27]:
lst.clear() #clear() is used to delete all items in the list
lst

[]

In [28]:
lst = [5,6,8,9,1,1,1]
lst

[5, 6, 8, 9, 1, 1, 1]

In [29]:
lst.index(8) #index() is used to identity index of the given value

2

In [30]:
lst.count(1) #count() is used to find how many time the number is repeated

3

In [31]:
lst.sort() # sort() is used to sort items present in the list
lst

[1, 1, 1, 5, 6, 8, 9]

In [32]:
lst.reverse() #reverse() is used to reverse the order of item present in the list
lst

[9, 8, 6, 5, 1, 1, 1]

2. Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [33]:
tup = ('prathap','sudeep','ravi') #creating a tuple
tup

('prathap', 'sudeep', 'ravi')

In [34]:
tup[1] = 'arjun'

TypeError: 'tuple' object does not support item assignment

TypeError: 'tuple' object does not support item assignment

ans= unlike list, the tuples are immutable. Once the tuple is created it cannot change, add, or remove any of its items/elements.

3. Create a set of integers with some duplicate values. Print the set and explain the output.

In [35]:
set1 = {1,2,8,6,7,2,8} #creating sets
set1

{1, 2, 6, 7, 8}

Explaination: A set in Python is an unordered collection of unique elements. When you create a set, duplicate values are automatically removed and sorted

that's why the output is (1,2,6,7,8)

4. Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.


In [36]:
dict = {'name': ['Sudeep','abhishek','pooja','aditya'],
        'age': [22,21,40,43], 
        'city': ['vijayapur','hubli','dharwad','mysore']}
dict

{'name': ['Sudeep', 'abhishek', 'pooja', 'aditya'],
 'age': [22, 21, 40, 43],
 'city': ['vijayapur', 'hubli', 'dharwad', 'mysore']}

In [ ]:
dict.setdefault('email', ['sudeep@gmail.com','abhi@gmail.com','pooja@gmail.com','aditya@gmail.com']) #adding a new key using setdefault
dict

{'name': ['Sudeep', 'abhishek', 'pooja', 'aditya'],
 'age': [22, 21, 40, 43],
 'city': ['vijayapur', 'hubli', 'dharwad', 'mysore'],
 'email': ['sudeep@gmail.com',
  'abhi@gmail.com',
  'pooja@gmail.com',
  'aditya@gmail.com']}

In [ ]:
dict.update({'age':[20,21,22,23]}) # update() used to update values
dict

{'name': ['Sudeep', 'abhishek', 'pooja', 'aditya'],
 'age': [20, 21, 22, 23],
 'city': ['vijayapur', 'hubli', 'dharwad', 'mysore'],
 'email': ['sudeep@gmail.com',
  'abhi@gmail.com',
  'pooja@gmail.com',
  'aditya@gmail.com']}

5. Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [ ]:
age = int(input("Enter the age")) 
if age>=18: # checks condition wheather the person is more than 18 age or not
    print("Eligible to vote")
else:
    print("Not Eligible to vote")

Eligible to vote


6. Given a 'marks' variable, print the grade: 
- 90 and above: 'A' 
- 75–89: 'B' 
- 50–74: 'C' 
- Below 50: 'Fail'

In [ ]:
marks = int(input("Enter the marks"))
print("Marks =",marks)
if marks >= 90:  #Checks condition for 90 and above: 'A'
    print("Grade = A")
if 75<=marks<=89: #Checks condition for  75–89: 'B' 
    print("Grade = B")
if 50<=marks<=74: #Checks condition for  50–74: 'C' 
    print("Grade = C")
if marks<50:      #Checks condition for  Below 50: 'Fail'
    print("Grade = Fail")

Marks = 56
Grade = C


7. Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [ ]:
number = int(input("Enter the number"))
if number > 0:  # Check if the number is positive
    if number % 2 ==0:  # If positive, check if it's even
        print("The number is positive and even")
    else:
        print("The number is positive and odd")
elif number==0: # Check if the number is zero
    print("The number is zero")
else:
    print("The number is negative")

The number is negative


#### Section B: Numpy

8. Create: 
- A scalar using np.array(5) 
- A 1D array with values 1 to 5 
- A 2D array (2x3) with values from 10 to 60 in steps of 10

In [66]:
import numpy as np

In [53]:
np.array(5)

array(5)

In [63]:
one_dim = np.array([1,2,3,4,5]) #Creating one dimention array
one_dim

array([1, 2, 3, 4, 5])

In [74]:
two_dim = np.arange(10,70,10).reshape(2,3) #Creating 2D array (2x3) with values from 10 to 60 in steps of 10
two_dim

array([[10, 20, 30],
       [40, 50, 60]])

9. Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [80]:
np.random.randint(0,100,16).reshape(4,4) #Generate a 4x4 Numpy array of random integers between 0 and 100

array([[73, 38, 51, 23],
       [16, 89, 98, 36],
       [57, 39, 11, 89],
       [64, 44, 25, 62]])

10. Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [ ]:
two = np.array([[2,3,4],[5,6,7],[8,9,5]]) #Creating 2D array of shape (3x3)
two

array([[2, 3, 4],
       [5, 6, 7],
       [8, 9, 5]])

In [84]:
import pandas as pd

In [89]:
df = pd.DataFrame(two,columns= ['A','B','C']) #Converting it into a pandas DataFrame and add column names: 'A', 'B', 'C'.
df

A  B  C
0  2  3  4
1  5  6  7
2  8  9  5

#### Section C: Exploring Pandas

11. Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then: 
- Use .info(), .describe() 
- Select 'Name' and 'City' columns 
- Drop 'City' column 
- Fill any missing values in 'Salary' column with the mean 
- Remove any duplicate rows

In [142]:
dict = {'Name' : ['adi','mani','gopi','abhi','joshi','kokila','chokila','srilila','vishal','binod'],
        'Age': [22,23,24,25,26,27,28,29,30,21],
        'City': ['vijayapur','hubli','bidar','bagalokot','benglore','udupi','mumbai','pune','delhi','mysore'],
        'Salary': [1000,2000,3000,1000,4000,5000,6000,7000,8000,9000]}
print(dict)

{'Name': ['adi', 'mani', 'gopi', 'abhi', 'joshi', 'kokila', 'chokila', 'srilila', 'vishal', 'binod'], 'Age': [22, 23, 24, 25, 26, 27, 28, 29, 30, 21], 'City': ['vijayapur', 'hubli', 'bidar', 'bagalokot', 'benglore', 'udupi', 'mumbai', 'pune', 'delhi', 'mysore'], 'Salary': [1000, 2000, 3000, 1000, 4000, 5000, 6000, 7000, 8000, 9000]}


In [128]:
df1 = pd.DataFrame(dict) 
df1

Name  Age       City  Salary
0      adi   22  vijayapur    1000
1     mani   23      hubli    2000
2     gopi   24      bidar    3000
3     abhi   25  bagalokot    1000
4    joshi   26   benglore    4000
5   kokila   27      udupi    5000
6  chokila   28     mumbai    6000
7  srilila   29       pune    7000
8   vishal   30      delhi    8000
9    binod   21     mysore    9000

In [ ]:
df1.info() #Display info about DataFrame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    10 non-null     object
 1   Age     10 non-null     int64 
 2   City    10 non-null     object
 3   Salary  10 non-null     int64 
dtypes: int64(2), object(2)
memory usage: 452.0+ bytes


In [ ]:
df1.describe() #Show statistical summary

Age       Salary
count  10.00000    10.000000
mean   25.50000  4600.000000
std     3.02765  2875.181154
min    21.00000  1000.000000
25%    23.25000  2250.000000
50%    25.50000  4500.000000
75%    27.75000  6750.000000
max    30.00000  9000.000000

In [ ]:
print(df1[['Name','City']]) #Select 'Name' and 'City' columns

      Name       City
0      adi  vijayapur
1     mani      hubli
2     gopi      bidar
3     abhi  bagalokot
4    joshi   benglore
5   kokila      udupi
6  chokila     mumbai
7  srilila       pune
8   vishal      delhi
9    binod     mysore


In [132]:
df1.drop(columns = ['City']) # droped column 'city'

Name  Age  Salary
0      adi   22    1000
1     mani   23    2000
2     gopi   24    3000
3     abhi   25    1000
4    joshi   26    4000
5   kokila   27    5000
6  chokila   28    6000
7  srilila   29    7000
8   vishal   30    8000
9    binod   21    9000

In [ ]:
df1.isnull().sum() # used to check missing null values
#If there are any missing values then we can use below code to fill missing values by filling with mean values
# mean_salary = df["Salary"].mean()
# df["Salary"] = df["Salary"].fillna(mean_salary)

Name      0
Age       0
City      0
Salary    0
dtype: int64

In [141]:
df1.duplicated().sum()
#if there are any dublicates use below line code
#df1.drop_duplicates() 

0